language: android

script:
   - ./gradlew build connectedCheck

android:
  components:
    
    # Tools
    - build-tools-25.0.2
    - android-25
    
    # Extras
    - extra-android-m2repository
    - extra-android-support
    - extra-google-m2repository
    
    # Emulator
    - sys-img-armeabi-v7a-android-22
    - sys-img-armeabi-v7a-android-25
