language: android
sudo: false
jdk: oraclejdk7
env:
  matrix:
    - ANDROID_TARGET=android-22  ANDROID_ABI=armeabi-v7a  ACDISPLAY_USE_TEST_KEY=true

android:
  components:
    - build-tools-22.0.1
    - android-22
    # Extras
    - extra-android-m2repository
    - extra-android-support
    - extra-google-m2repository
    # Emulator
    - sys-img-armeabi-v7a-android-22
  lintOptions {
          abortOnError false
      }

before_script:
  - echo no | android create avd --force -n test -t android-19 --abi armeabi-v7a
  - emulator -avd test -no-skin -no-audio -no-window &
  - android-wait-for-emulator
  - adb shell input keyevent 82 &
