language: android

android:
  components:
    - platform-tools
    - tools
    - build-tools-25.0.2
    - android-25
    # Extras
    - extra-android-m2repository
    - extra-android-support
    - extra-google-m2repository

script: ./gradlew connectedCheck 
